name: secop

services:
  postgresdb:
    image: postgres:13
    container_name: db.postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:${POSTGRES_INTERNAL_PORT}"
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data
    networks:
        - internal

  rabbitmq: 
    container_name: queue.rabbitmq
    image: rabbitmq:3-management
    restart: always
    volumes:
        - rabbitmq-data-volume:/var/lib/rabbitmq/
        - rabbitmq-data-volume:/var/log/rabbitmq/
    networks:
        - internal


  # elasticsearch:  
  #   container_name: elk.elasticsearch
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
  #   volumes:
  #       - elk-data-volume:/usr/share/elasticsearch/data
  #   environment:
  #       - xpack.monitoring.enabled=true
  #       - xpack.watcher.enabled=false
  #       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #       - discovery.type=single-node
  #   networks:
  #       - internal
  
  # kibana:
  #   container_name: elk.kibana
  #   image: docker.elastic.co/kibana/kibana:7.16.2
  #   depends_on:
  #       - elasticsearch
  #   networks:
  #       - internal

  # redisdb:
  #  container_name: db.redis
  #  image: redis:6.2-alpine
  #  restart: always
  #  command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
  #  volumes: 
  #    - redis-data-volume:/data
  #  networks:
  #       - internal

  mongodb:
   container_name: db.mongodb
   image: mongo
   restart: always
   volumes:
       - mongo-data-volume:/var/lib/mongodb/data
       - mongo-data-volume:/var/lib/mongodb/configdb
   networks:
       - internal

  ############################### sagastatemachine ###############################
  sagastatemachine:
    image: ${DOCKER_REGISTRY-}secop/sagastatemachine
    container_name: worker.sagastatemachine
    depends_on:
        - credit.api.v2
        - approval.api.v2
        - customer.api.v1
        - score.api.v2
        - repayment.api.v2
        - notification.api.v2 
        - mongodb
    build:
      context: ./../src
      dockerfile: WorkerServices/Secop.WorkerServices.SagaStateMachine/Dockerfile
    networks:
        - internal

############################### gateway ###############################
  gateway.api:
    image: ${DOCKER_REGISTRY-}secop/gateway
    container_name: api.gateway
    depends_on:
        - credit.api.v1
        - approval.api.v1
        - customer.api.v1
        - score.api.v1
        - postgresdb
        - rabbitmq
    build:
      context: ./../src
      dockerfile: Gateway/Secop.Gateway.Api/Dockerfile
    networks:
        - internal


############################### approval ###############################
  approval.api.v1:
    image: ${DOCKER_REGISTRY-}secop/v1/approval
    container_name: api.v1.approval
    depends_on:
        - postgresdb
        - rabbitmq
    build:
      context: ./../src/Services
      dockerfile: Approval/Secop.Approval.Web.Api.V1/Dockerfile
    networks:
        - internal

  approval.api.v2:
    image: ${DOCKER_REGISTRY-}secop/v2/approval
    container_name: api.v2.approval
    depends_on:
        - postgresdb
        - rabbitmq
    build:
      context: ./../src/Services
      dockerfile: Approval/Secop.Approval.Web.Api.V2/Dockerfile
    networks:
        - internal


############################### credit ###############################
  credit.api.v1:
    image: ${DOCKER_REGISTRY-}secop/v1/credit
    container_name: api.v1.credit
    depends_on:
        - postgresdb
        - rabbitmq
    build:
      context: ./../src/Services
      dockerfile: Credit/Secop.Credit.Web.Api.V1/Dockerfile
    networks:
        - internal


  credit.api.v2:
    image: ${DOCKER_REGISTRY-}secop/v2/credit
    container_name: api.v2.credit
    depends_on:
        - postgresdb
        - rabbitmq
    build:
      context: ./../src/Services
      dockerfile: Credit/Secop.Credit.Web.Api.V2/Dockerfile
    networks:
        - internal


############################### customer ###############################
  customer.api.v1:
    image: ${DOCKER_REGISTRY-}secop/v1/customer
    container_name: api.v1.customer
    depends_on:
        - postgresdb
        - rabbitmq
    build:
      context: ./../src/Services
      dockerfile: Customer/Secop.Customer.Web.Api.V1/Dockerfile
    networks:
        - internal


############################### score ###############################
  score.api.v1:
    image: ${DOCKER_REGISTRY-}secop/v1/score
    container_name: api.v1.score
    depends_on:
        - postgresdb
        - rabbitmq
    build:
      context: ./../src/Services
      dockerfile: Score/Secop.Score.Web.Api.V1/Dockerfile
    networks:
        - internal

  score.api.v2:
    image: ${DOCKER_REGISTRY-}secop/v2/score
    container_name: api.v2.score
    depends_on:
        - postgresdb
        - rabbitmq
    build:
      context: ./../src/Services
      dockerfile: Score/Secop.Score.Web.Api.V2/Dockerfile
    networks:
        - internal

############################### repayment ###############################
  repayment.api.v2:
    image: ${DOCKER_REGISTRY-}secop/v2/repayment
    container_name: api.v2.repayment
    depends_on:
        - postgresdb
        - rabbitmq
    build:
      context: ./../src/Services
      dockerfile: Repayment/Secop.Repayment.Web.Api.V2/Dockerfile
    networks:
        - internal

############################### notification ###############################
  notification.api.v2:
    image: ${DOCKER_REGISTRY-}secop/v2/notification
    container_name: api.v2.notification
    depends_on:
        - rabbitmq
    build:
      context: ./../src/Services
      dockerfile: Notification/Secop.Notification.Web.Api.V2/Dockerfile
    networks:
        - internal

volumes:
  postgres-data-volume:
  rabbitmq-data-volume:
  elk-data-volume:
  mongo-data-volume:
  redis-data-volume:

networks:
    internal:
        driver: bridge
